### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/containers#1]
```yaml
      - name: Install dependencies
        run: |
          dnf install -y \
            podman skopeo buildah zstd
```
